#Tested on 4.22+
# Subscriptions to OpenConfig paths.
subscriptions:
        - /network-instances/network-instance[name=default]/protocols/protocol[identifier=BGP][name=BGP]/bgp
        - /system/processes
        - /interfaces/interface
# Prometheus metrics configuration.
# If you use named capture groups in the path, they will be extracted into labels with the same name.
# All fields are mandatory.
metrics:
        - name: BgpPfxReceived
          path: /network-instances/network-instance\[name=default\]/protocols/protocol\[identifier=BGP\]\[name=BGP\]/bgp/neighbors/neighbor\[neighbor-address=(?P<neighbor>.+)\]/afi-safis/afi-safi-name=\[openconfig-bgp-types:IPV4_UNICAST\]/state/prefixes/received
        - name: BgpPfxInstalled
          path: /network-instances/network-instance\[name=default\]/protocols/protocol\[identifier=BGP\]\[name=BGP\]/bgp/neighbors/neighbor\[neighbor-address=(?P<neighbor>.+)\]/afi-safis/afi-safi-name=\[openconfig-bgp-types:IPV4_UNICAST\]/state/prefixes/installed
        - name: BgpPfxSent
          path: /network-instances/network-instance\[name=default\]/protocols/protocol\[identifier=BGP\]\[name=BGP\]/bgp/neighbors/neighbor\[neighbor-address=(?P<neighbor>.+)\]/afi-safis/afi-safi-name=\[openconfig-bgp-types:IPV4_UNICAST\]/state/prefixes/sent
        - name: BGPCPU
          path: /system/processes/process\[pid=2794\]/state/cpu-utilization
        - name: intfCounter
          path: /interfaces/interface\[name=(?P<intf>[^\]]+)\]/state/counters/(?P<countertype>.+)
